#server:
#  port: 8761
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://47.107.104.181:8086/eureka
#      defaultZone: http://localhost:8761/eureka/
  server:
    enable-self-preservation: false
spring:
  application:
    name: eureka-server
