spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MuggleLee/microservice-config
          username: MuggleLee
          password: 369874125lihao.
          basedir: E:\microservice-config
eureka:
  client:
    service-url:
      defaultZone: http://47.107.104.181:8761/eureka